### ISSUE TITLE
Update repository description to be more accurate 🤓

### ISSUE THREAD

**Issue by Ambient-Impact** [8fold/commonmark-abbreviations#11]
The repository about is currently "An extension of PHP League", but it would be more accurate to say

> An extension for league/commonmark.

 or

> An extension for the CommonMark parser by the League of Extraordinary Packages.

See the [their website](https://thephpleague.com/) and their [GitHub namespace](https://github.com/thephpleague).

**Comment by joshbruce** [comment]
Good call

**Comment by Ambient-Impact** [comment]
![pusheen_typing_on_laptop](https://user-images.githubusercontent.com/2289006/118171916-c3e93000-b3f9-11eb-895e-1a3c464a08a1.gif)
