### ISSUE TITLE
Test failing because of missing Shoop dependency.

### ISSUE THREAD

**Issue by Ambient-Impact** [8fold/commonmark-abbreviations#5]
**Describe the bug**
```composer install``` and then ```phpunit``` fails due to ```Error: Class 'Eightfold\Shoop\Shoop' not found``` 😓

**To Reproduce**
See above

**Expected behavior**
Test should not fail due to missing dependency.

-----

I see that this was removed from the non-dev ```require``` in 88bd000dd23fb9242e1cabf7296da733e22688de, but still used in the tests. If I ```composer require "8fold/php-shoop:~0.5" --dev```, I then get ```Error: Call to undefined method Eightfold\Shoop\Shoop::string()```. 😱

**Comment by joshbruce** [comment]
Hello! Thanks for letting me know.

I've added this to my more general list of tasks.

Given the prioritization at the moment, it might take a moment. In the meantime 

I've labeled it as annoying as it doesn't affect package operation (outside of CI/CD), which means it's higher priority than new features and whatnot in that longer list.

If you would like (or need) it earlier to be comfortable using the package, let me know or please feel free to submit a PR.

Also, thank you for letting us know we're not the only ones using this package - always enjoy meeting a fellow user.

**Comment by joshbruce** [comment]
Spoke too soon. Higher priority given after realizing I couldn't install it locally as it has been updated to accept PHP 8 environments.

Thanks again!

**Comment by Ambient-Impact** [comment]
Glad to help!
